version: '3.7'

services:
  mysql-database:
    image: mysql:5.7
    container_name: mysql-woowahan
    environment:
      MYSQL_DATABASE: BookContents
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: sa
      MYSQL_PASSWORD: password
      TZ: Asia/Seoul
    ports:
    - 3306:3306
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci